# Uses the contents of the ./docs directory for Shipyard's GH Wiki page
name: 📊 Wiki Sync
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master        
    - name: Upload Docs to GH Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        GH_PAT: ${{ secrets.ORG_REPO_TOKEN || secrets.GITHUB_TOKEN }}
        ACTION_MAIL: khulnasoft-gh-bot@mail.as93.net
        ACTION_NAME: khulnasoft-bot
        OWNER: KhulnaSoft-bot
        REPO_NAME: Shipyard
        MD_FOLDER: docs/
#     - name: Sync Wiki
#       uses: joeizzard/action-wiki-sync@master
#       with:
#         username: example
#         access_token: ${{ secrets.GITHUB_TOKEN }}
#         wiki_folder: ./docs
#         commit_username: 'khulnasoft-bot'
#         commit_email: 'khulnasoft-bot@khulnasoft.com'
#         commit_message: '📕 Chore: Sync Wiki'
